version: '2.1'
networks:
   default:
      external:
         name: spring-cloud-network
services:
  chcp-server:
    container_name: chcp-server
    volumes:
      - ./www:/usr/share/nginx/html:ro
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=chcp.61topbaby.com
      - LETSENCRYPT_HOST=chcp.61topbaby.com
      - LETSENCRYPT_EMAIL=qing.wang@61topbaby.com
    ports:
      - 10080:80